services:
  db:
    image: postgres:15-alpine
    container_name: mailmind_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mailmind
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mailmind_redis
    restart: always
    ports:
      - "6381:6379"

  backend:
    build: ./backend
    container_name: mailmind_backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/mailmind
      - REDIS_URL=redis://redis:6379/0
      - GOOGLE_REDIRECT_URI=http://localhost:8000/api/v1/auth/callback
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    container_name: mailmind_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend

volumes:
  pgdata:
